name = ship_parts
depends = default, ctg_world, ctg_airs, ctg_jetpack, technic, pipeworks, digilines, scifi_nodes
optional_depends = ctg_quartz, ctg_ruby, ctg_sapphire, ctg_emerald
description = Adds Ship Parts.
